apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:                      # Labels for the replicaSet
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80