# Secret [ kubernetes secres support only base64 format ]
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  # property-like keys; each key maps to a simple value
  dbusername: "ZGJhbWluCg=="
  dbpassword: "ZHBhMTMjcHdkCg=="
  token: "dHJteWxta2Roa2xoc2ozcjR0ZHNmZyoqcTQzCg=="
  .secret-file: dmFsdWUtMg0KDQo=

--- 
apiVersion: v1
kind: Pod
metadata:
  name: game-pod
spec:
  containers:
    - name: app
      image: docker.io/nginx:latest
      envFrom:
        - secretRef:
            name: secret-demo