apiVersion: v1
kind: Pod
metadata:
  name: print-greeting
spec:
  containers:
  - name: env-print-demo
    image: nginx
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: TOPIC
      value: "Kubernetes"
    - name: Config
      value: "map"
    - name: SAMP
      value: "debug"