# Secret 
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-demo
data:
  # property-like keys; each key maps to a simple value
  dbusername: "dbamin"
  dbpassword: "dpa13$pwd"
  token: "trmylmkdhklhsj3r4tdsfg**q43"

--- 
apiVersion: v1
kind: Pod
metadata:
  name: game-pod
spec:
  containers:
    - name: app
      image: docker.io/nginx:latest
      envFrom:
        - configMapRef:
            name: secret-demo