apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-demo-cpu-mem-count
  namespace: namespace
spec:
  hard:
    pods: "2"
    requests.cpu: "500"
    requests.memory: "5Gi"
    limits.cpu: "600"
    limits.memory: "10Gi"
  