# Vertical Pod Autosclaing### HPA : Horizonal Pod Autoscaling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker.io/nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "100m"

--- 
# Provisions VPA 
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: frontend-vpc
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       frontend 
  updatePolicy:
    updateMode: "Auto"