apiVersion: v1
kind: Pod
metadata:
  name: large
  labels:                      # Labels for the replicaSet
    tier: large
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "6000Mi"
        cpu: "500mm"
      limits:
        memory: "8000Mi"
        cpu: "800m"

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: heavy-pod
# spec:
#   containers:
#   - name: app
#     image: docker.io/nginx
#     resources:
#       requests:
#         memory: "6000Mi"
#         cpu: "500mm"
#       limits:
#         memory: "8000Mi"
#         cpu: "800m"
