apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
  labels:
    app: topology
spec:
  replicas: 3
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: topology
      containers:
      - name: topology
        image: docker.io/nginx:perl
        ports:
        - containerPort: 80
