apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
  labels:
    app: topology
spec:
  topologySpreadConstraints:
    - maxSkew: 1
  replicas: 5
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
      - name: topology
        image: docker.io/nginx:perl
        ports:
        - containerPort: 80
