apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  labels:                      
    tier: {{ .Values.appName }}
spec:
  containers:
  - name: {{ .Values.appName }}
    image: docker.io/sanraman/expense-{{ .Values.appName }}
    ports:
    - containerPort: {{ .Values.port }}
