apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    tier: {{ .Values.appName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}                 
      targetPort: {{ .Values.port }}  